Algoritmo "4 I"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exercício I página 41
// Autor(a)    : Rian Alves Cadamuro
// Data atual  : 01/09/2023
Var
num: inteiro

Inicio
// Entrada de dados
Escreva("Digite um número: ")
Leia(num)

//processamento
Se (num%2=0) entao
   Escreva("O número é par")
Senao
   Escreva("Ele é impar")
Fimse
Fimalgoritmo