Algoritmo "4 J"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : exercicio 4
// Autor(a)    : Rian Alves Cadamuro
// Data atual  : 28/08/2023
Var
numero: inteiro


Inicio
// entrada de dados
Escreva("Digite um número: ")
Leia(numero)

//processamento:
Se (10> numero) e (numero>0) entao
   Escreva("O número está na faixa")
Senao
     Escreva("INFELIZMENTE, o número não se encaixa.")
Fimse

Fimalgoritmo